name: Newman Tests
on:
  push:
    branches: [ newman ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Newman
      run: npm install -g newman
    - name: Run Newman
      run: newman run newman/01/collection-env.json -d newman/01/data.csv
