version: "3"
services:
  PS:
    image: prestashop/prestashop:1.7.8.2
    volumes:
      - ./data:/var/www/html 
    ports:
      - "8099:80" 
    restart: always

  DB:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=userps
      - MYSQL_PASSWORD=passps
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db:/var/lib/mysql
